### ISSUE TITLE
What if Service Provider !== Instantiator?

### ISSUE THREAD

**Issue by schlessera** [container-interop/service-provider#30]
Hey all,

I'm currently looking through the proposals here to see what "standardized" interfaces I could support in my architecture. Well I "somehow" support the `ContainerInterface` (for my use case, it would absolutely need some form of `put()` or `set()`), I can't see how I would be able to support the `ServiceProviderInterface`. I wanted to talk about what my issues are so it might help locate friction points in the current interface.

The current `ServiceProviderInterface` makes a very big assumption: the component providing the service is also the one that is responsible for instantiating it. In my architecture this is not the case, and I went through a lot of trouble to make it this way. I specifically have two different containers (a "Service Locator", and a "Dependency Injector"), and the components providing the services are neither of these.

In my use case, the flow is basically the following:
When a new component (think module/extension/plugin) is loaded, it registers its Service Provider with the Service Locator. The Service Locator then first asks it to provide its mappings. These are "interface=>class" or "class=>class" mappings that get passed to the Dependency Injector. Then it asks what Services need to be registered, which is an array of "name=>interface" or "name=>class" mappings. It just stores these, nothing gets instantiated yet.

When a Service is retrieved, the Service Locator looks at the "interface/class" it needs and asks the Dependency Injector to instantiate it. By then, the Dependency Injector might have received additional mappings, so the Service Provider and the Service Locator completely ignore what exact class the Dependency Injector will instantiate, they just know that it will implement the "interface/class" that the Service Provider had originally asked for.

So, in such a use case, having the Service Provider provide a callable would force the Service Provider to both know about the exact Service Locator and Dependency Injector just to make this instantiation, which should not be its responsibility, IMHO. Having all of the instantiation be done through a Dependency Injector lets me properly couple all of my code exclusively against interfaces, which would not be possible with the current implementation of the `ServiceProviderInterface`.

I would love to hear about your opinions on this subject. I seem to have noticed that not everyone is a fan of runtime decisions and auto-wiring dependency injectors. I think it depends on the use case, and is a trade-off between several factors. In my case, the benefits of keeping the code as flexible as possible, while allowing me to do all sorts of optimizations after the fact, when I have effectively identified a real bottleneck in practice, far outweighs any disadvantages.

**Comment by mnapoli** [comment]
Hi! I'm not sure I understand what the problem :) I've re-read the issue a couple times but I'm still not sure.

However:

> The current ServiceProviderInterface makes a very big assumption: the component providing the service is also the one that is responsible for instantiating it.

I want to emphasize that the current proposal's goal is: an interoperable container config. That is meant to be used for cross-framework modules **only**.

**It isn't meant to force how containers/frameworks implement their own modules.** In other words, it's fine if your container/framework has its own syntax/architecture/system for its modules, and it's fine if it's not compatible with this standard.

What matters is that your container/framework can still load those cross-framework modules.

To give you a more concrete example in my case: PHP-DI config files will not change to be compatible with ServiceProviderInterface. PHP-DI's architecture stays the same. However PHP-DI will be able to accept standard service providers (on top of the existing system). That way cross-framework modules can be used with PHP-DI, but users (of PHP-DI) can still use the features of PHP-DI in their own application (where interoperability doesn't matter because their application will not be distributed as a "generic module").

I'm not sure if it answers the original question.

**Comment by mindplay-dk** [comment]
I also do not fully understand the problem - but @mnapoli has answered the question, I have nothing to add, and OP has not responded, thus, closing.
