### ISSUE TITLE
Symfony DI

### ISSUE THREAD

**Issue by theofidry** [container-interop/service-provider#35]
Whilst there is a few things I'm not fond of in Symfony, I must say really appreciate the Symfony DI despite some shortcomings. It may seems like a dumb idea to some but what about picking it up as a standard?

A few reasons:

- Is mature and battle tested in different formats (PHP, YAML, XML)
- Handles well all the cases I can think of:
  - regular service
  - abstract services
  - aliases
  - factories
  - decorators
  - tagging
  - lazy instantiation
  - autowiring

The idea behind it is really simple: having a `Definition` describing the service to be instantiated. The advantage of that is that it makes it really easy to have bridges for different frameworks and is relatively flexible.

I remember porting Symfony DI YAML config to Laravel [LaravelYaml](https://github.com/theofidry/LaravelYaml) (not all features though as we didn't need all of them) once for a private application and was really happy about the result. The trouble was really about the resolution of the parameters, the reset about the service registration itself was rather smooth.

There is definitely once problem or two that would require to be addressed still, but I think it would be great to base the work on a well established DI.

I must say after looking at the current work, as a library maintainer that would *love* to provide support to different frameworks by having to register my services only once, the current implementation doesn't looks very appealing. That said, I may have missed something...

**Comment by mnapoli** [comment]
Hi @theofidry, this is an interesting question because I believe others will ask themselves the same thing.

> what about picking it up as a standard?

I think there are several different things here:

- make Symfony's *container* a standard
- make Symfony's YAML config files (or XML config files) the standard

I believe you meant the second option because the first is basically saying "let's not use any alternative to Symfony" and PHP devs today are definitely doing that, so there would be no incentive for them to do that. Correct me if I'm wrong.

So, **if** you meant the second option, here are a few issues I see with that:

### it forces all containers to implement all the features of Symfony

That's a major issue. The same team that wrote Symfony DI also wrote Pimple, and that's for a reason. Adding all these features to Pimple would make it, well, Symfony DI, so again it doesn't make sense: Pimple solves a need that Symfony DI doesn't.

You could argue "Yes but let's do that only for interop packages, Pimple users can still use the simple API/ArrayAccess" => right but then why don't Symfony DI support ArrayAccess/Pimple usage? There are many (good) reasons for why that's not the case today.

For example, it means all containers would have to implement autowiring, tags, decorators, lazy loading, etc. That's just not realistic, some containers (again like Pimple but like many others) exist to provide a simple and light solution so they wouldn't want to implement it. We also should note that implementing all those features is a huuuge deal of work and most containers simply couldn't implement it, even if they wanted to.

### those config files and features are a performance killer for non-compiled containers

Tags, for example, are completely incompatible with not-compiled containers (for performance reasons). That's why everything in Pimple is done with decorators. That's also one of the reason why in PHP-DI I used PHP arrays and decorators.

Implementing all the features would make every container out there slow as heck, leaving Symfony as the only viable alternative (the vast majority of containers are not compiled).

The only solution would be for everyone to go "compiled", but that's not a good idea. There are issues with compiled containers, for example on the top of my head:

- the configuration cannot be dynamic (e.g. overriding services on the fly in Symfony in tests is a huge pain, with other containers it's super easy)
- the user experience is worse -> that can be a huge deal for some projects where users should be able to drag and drop code on a FTP server, or e.g. modules => I've seen that issue firsthand in Piwik
- the parameters cannot be dynamic => just look at the mess it was supporting env variables in Symfony. Some applications load parameters from Redis or database or whatever, adding support for that with compiled containers is a PITA

I used to be really interested in compiling for PHP-DI but after trying it, limitations really show. There's a reason not everyone uses Symfony: it doesn't fit every use case.

### Symfony's config files are very opinionated

Well it's not a full reason per se but mixing service/parameters configuration with actual configuration that is read by compilation passes and DI extensions to be turned into actual service config on the fly, etc. That's very Symfony, it works well with Symfony bundles, but it's very specific to Symfony. I haven't seen any other container that push so far the "configuration of configuration" concept (in Symfony you actually configure bundles that will generate the configuration in compilation passes).

### It doesn't cover all use cases

While Symfony DI is very rich feature-wise, it's not complete. For example you can't just write a PHP closure to configure a service. And that's what 60-80% of all the other containers allow.

### Symfony config files are not "self-contained"

What I mean by that is that you can write a YAML/XML config files with services and tag them, but the behavior behind the tag is unknown at that point. You **need** to write a compilation pass. Without that the tag doesn't do anything. That's a big issue I would say because we would need another standard for that (and what would that mean for non-compiled containers?) :)

---

Well that's just what's on the top of my head, maybe I missed obvious things. I don't even want to discuss the political challenges because it's more interesting to discuss technical stuff first ;)

**Comment by mnapoli** [comment]
Also I didn't start with that but: I use Symfony everyday and the DIC is absolutely amazing in terms of engineering, I have a lot of respect for the work and the people behind it. I am not trying to shoot down this idea blindly ;)

**Comment by theofidry** [comment]
Thanks for the complete breakdown @mnapoli :) I had a quick chat in the meantime with someone who pointed those performance issues to me, you just broken that done in a much more detailed and elaborated way.

A few more questions still:

- What is the scope of this service provider PSR? I mean out of all the features I mentioned (I may have missed one), what are the ones that are covered by the PSR? Is the plan having only one PSR fitting most common use cases without pushing too far or is the plan to have 2 standards like the cache: a minimalistic one and a more advanced one?

- Configuration of services via non PHP config files could still be done thanks to a generator. I.e., instead of having a config file parsed at runtime, it could be possible to have a generator tool to parse the config file and dump the php service provider. The author of a library would then have to (if he wishes to use a config file) make sure his XML/YAML config file is in sync with this service provider. May not be quite as smooth has having none, but could be an acceptable trade-off for having config files. That said, this highly depends on the features this PSR will include, if it's "just" registering a closure or a factory, it's certainly not worth the trouble.

**Comment by mnapoli** [comment]
> - What is the scope of this service provider PSR?

To quote your feature list:

> regular service

:+1:

> abstract services

Do you mean reusable generic service definitions? It could be done via an abstract factory.

> aliases

https://github.com/container-interop/service-provider#aliases

> factories

:+1: (because everything is a factory

> decorators

https://github.com/container-interop/service-provider#entry-extension

> tagging

If you want to handle lists there's https://github.com/container-interop/service-provider#entry-extension that you can use for arrays or whatever, do you have something else in mind?

> lazy instantiation

It's not included, but it's possible. Since you write your factory, you can use ProxyManager (or whatever) to create and return a proxy. As you can see it's up to you, however it's a very rare and specific use case so it's perfectly fine (we are talking about a standard whose goal is to solve 80-90% of the cases).

> autowiring

Same as lazy instantiation, one could easily build an "autowiring" helper or service provider. Since the standard targets module authors (not end users or framework authors) autowiring is not really a big issue.

---

The main point of all this is that you bind a service to PHP code, that's as generic and as open as it can get. Pimple (and many other containers) work that way, and it works really well. All this is basically a more generic standardization of Pimple's service providers.

For a more complete answer about features I invite you to read:

- https://github.com/container-interop/fig-standards/blob/container-configuration/proposed/container-configuration-meta.md#631-features
- and more importantly https://github.com/container-interop/fig-standards/blob/container-configuration/proposed/container-configuration-meta.md#632-feature-support

We listed a lot of features there.

---

> - Configuration of services via non PHP config files could still be done thanks to a generator.

Yep but if you need to use the generator then why bother with the config file at all? If we take that suggestion the other way we could standardize service providers instead (i.e. the equivalent of the generated code), then you could also write config in YML and use the generator to dump the standard service provider?

**Comment by theofidry** [comment]
>then you could also write config in YML and use the generator to dump the standard service provider?

Yes that's what I had in mind, sorry my explanation was not clear.

Thanks again for the answer, I'll try to use it for https://github.com/nelmio/alice if I find some time for it :)
