### ISSUE TITLE
Ready to tag a new release?

### ISSUE THREAD

**Issue by prisis** [container-interop/service-provider#38]

**Comment by moufmouf** [comment]
Hey @prisis 

I just opened a new PR ( #39 ) about an issue that has been discussed from almost a year.

Do you need a tag for PSR-11 quickly or can it wait until this PR is discussed?

From my understanding, nothing should prevent you from using v0.3.0 with PSR-11 (as the `Interop\Container\ContainerInterface` now extends the `Psr\Container\ContainerInterface`)

So the only breaking change is the interface name. Since there are more breaking changes to come in the near future, do you really need a tagged release now? I'd rather bundle more changes in the next release (I have a big number of service providers to migrate and it's exhausting to do this twice)

**Comment by prisis** [comment]
Hey @moufmouf, no i can wait a bit :), need to migrate some providers too :D
